name: CI/CD - Heart Disease API

on:
  push:
    branches: [main, master]

env:
  PROJECT_ID: project-5e847658-f172-4998-bd0
  GKE_CLUSTER: heart-disease-cluster
  GKE_ZONE: us-central1-a
  IMAGE: us-central1-docker.pkg.dev/project-5e847658-f172-4998-bd0/heart-disease-api/heart-disease-api
  WIF_PROVIDER: projects/262041725178/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  WIF_SA: github-actions-sa@project-5e847658-f172-4998-bd0.iam.gserviceaccount.com

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WIF_PROVIDER }}
        service_account: ${{ env.WIF_SA }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: gke-gcloud-auth-plugin

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build & Push
      run: |
        docker build -t $IMAGE:$GITHUB_SHA -t $IMAGE:latest ./app
        docker push $IMAGE:$GITHUB_SHA
        docker push $IMAGE:latest

    - name: Get GKE credentials
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        sed -i "s|:latest|:$GITHUB_SHA|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout status deployment/heart-disease-api
